# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SX1tpLRshAagpRrcd0XX8Eu65vDOAVsM
"""

# Dataset from image
data = [
    (25, 40000, 'N'),
    (35, 60000, 'N'),
    (45, 80000, 'N'),
    (20, 20000, 'N'),
    (35, 120000, 'N'),
    (52, 99000, 'Y'),
    (23, 18000, 'Y'),
    (40, 62000, 'Y'),
    (60, 100000, 'Y'),
    (48, 220000, 'Y'),
    (33, 150000, 'Y')
]

query_age = 48
query_loan = 142000

# Distance calculation
distances = []
for age, loan, cls in data:
    d = abs(age - query_age)*1000 + abs(loan - query_loan)
    distances.append((age, loan, cls, d))

# Sort by distance
distances.sort(key=lambda x: x[3])

# Take K = 3 nearest
k = 3
nearest = distances[:k]

# Majority voting
votes = {'Y': 0, 'N': 0}
for item in nearest:
    votes[item[2]] += 1

print("Nearest Neighbours:")
for n in nearest:
    print(n)

print("\nPredicted Class:", max(votes, key=votes.get))

import matplotlib.pyplot as plt

# Dataset (from your notebook)
ages = [25, 35, 45, 20, 35, 52, 23, 40, 60, 48, 33]
loans = [40000, 60000, 80000, 20000, 120000, 99000, 18000, 62000, 100000, 220000, 150000]

# Query point
query_age = 48
query_loan = 142000

# Plot
plt.figure()
plt.scatter(ages, loans)
plt.scatter(query_age, query_loan, marker='x', s=100)

plt.xlabel("Age")
plt.ylabel("Loan Amount")
plt.title("Age vs Loan Amount (KNN Classification)")

plt.show()