# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dKoIhX1af0nvsZY-Jym19Z7PHKq3OCEl
"""

from google.colab import files
files.upload()

with open("sample.log", "r", errors="ignore") as f:
    for line in f:
        print(line.strip())

with open("sample.log", "r", errors="ignore") as f:
    cleaned = f.read()

with open("cleaned_log.log", "w") as f:
    f.write(cleaned)

from google.colab import files
files.download("cleaned_log.log")