# -*- coding: utf-8 -*-
"""LinearRegression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mRoCMI5QaICXMfs5NYJ4iTPPMWOt37X6
"""

import numpy as np
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt

# Sample data
X = np.array([[1], [2], [3], [4], [5]])   # features
y = np.array([2, 4, 5, 4, 5])             # target

# Model
model = LinearRegression()
model.fit(X, y)

# Predictions
y_pred = model.predict(X)

# Print results
print("Slope (Coefficient):", model.coef_[0])
print("Intercept:", model.intercept_)

# Plot
plt.scatter(X, y)
plt.plot(X, y_pred)
plt.xlabel("X")
plt.ylabel("y")
plt.title("Linear Regression")
plt.show()



from google.colab import files
uploaded = files.upload()

import pandas as pd

# Get the uploaded file name
filename = list(uploaded.keys())[0]

# Load the CSV
df = pd.read_csv('housing.csv')
print("Data Loaded Successfully!")
print(df.head())

# Corrected: Use actual column names from housing.csv for X and y
X = df[['housing_median_age']] # Using 'housing_median_age' as the feature
y = df['median_house_value']    # Using 'median_house_value' as the target

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LinearRegression
model = LinearRegression()
model.fit(X_train, y_train)

print("Model Trained!")
print("Slope:", model.coef_[0])
print("Intercept:", model.intercept_)

y_pred = model.predict(X_test)
print("\nPredictions on Test Data:")
print(y_pred)

import matplotlib.pyplot as plt

plt.scatter(X, y)               # original scatter plot
plt.plot(X, model.predict(X), color='red') # Plot the regression line
plt.xlabel("Housing Median Age") # Updated label
plt.ylabel("Median House Value")  # Updated label
plt.title("Linear Regression Result")
plt.show()